version: 1
accounts:
  - name: validator1
    coins: [ "200000000smpl" ]
    mnemonic: "blossom nominee burst use banana base kite strong lawn autumn tree enact vapor domain media you marble bomb theory heart visit give cereal panic"
  - name: alice
    coins: [ "200000smpl" ]
    mnemonic: "primary off palace rhythm attend human sample exact side domain fantasy attend tent end shadow gallery okay gallery clog announce cry senior citizen spot"
  - name: bob
    coins: ["10000smpl"]
    mnemonic: "lion fade special man proof bus mansion turn consider earth castle comfort echo axis body pen vehicle glare pig chest member fantasy brush kiwi"
validators:
  - name: validator1
    bonded: "10000000smpl"
client:
  openapi:
    path: "docs/static/openapi.yml"
  typescript:
    path: "ts-client"
  vuex:
    path: "vue/src/store"
genesis:
  chain_id: "cosmos:smpl-chain"
  app_state:
    staking:
      params:
        bond_denom: "smpl"
    crisis:
      constant_fee:
        denom: smpl
    mint:
      params:
        mint_denom: smpl
    bank:
      denom_metadata:  
        - description: "Pegged USD token"
          name: "usdse"
          symbol: "usdse"
          display: "usdse"
          base: "usdse"
          denom_units: 
             - denom: "usdse"
               exponent: 0
             - denom: "usdsed"
               exponent: 2
    roles:
      adminaccount: "smpl1q28v96p6lhyac2ghjlyylsl4290tl722x9kmtg"
faucet:
  name: alice
  coins:
    - 1000smpl
  coins_max:
    - 20000smpl
init:
  app:
    minimum-gas-prices: "0smpl"
    grpc-web:
      enable-unsafe-cors: false
    api:
      enabled-unsafe-cors: false
  client:
    keyring-backend: test
    chain-id: "cosmos:smpl-chain"
