version: "3"
services:
  SmplChain:
    build: .
    image: registry.digitalocean.com/smplfinance-image-registry/smpl-chain:3.0.0

  ReverseProxy:
    build:
      context: .
      dockerfile: ReverseProxyDockerfile
    image: registry.digitalocean.com/smplfinance-image-registry/smpl-chain-reverse-proxy:1.0.0
    depends_on:
      - SmplChain
    ports:
      - "1318:1318"
      - "26658:26658"

